import { Service } from '@angular/core';
import { Crop } from '../model/crops/crop.type';

@Service()
export class CropsService {

corps : Array<Crop>= [
    { id: 1, name: 'Wheat', description: 'A cereal grain used for making flour.' },
    { id: 2, name: 'Corn', description: 'A versatile crop used for food and fuel.' },
    { id: 3, name: 'Rice', description: 'A staple food for a large part of the world\'s population.' },
    { id: 4, name: 'Soybeans', description: 'A legume used for oil and protein products.' },
    { id: 5, name: 'Barley', description: 'A cereal grain used in brewing and animal feed.' },
    { id: 6, name: 'Oats', description: 'A cereal grain used for food and livestock feed.' },
    { id: 7, name: 'Potatoes', description: 'A starchy tuber used as a food crop.' },
    { id: 8, name: 'Tomatoes', description: 'A fruit used in cooking and salads.' },
    { id: 9, name: 'Carrots', description: 'A root vegetable rich in beta-carotene.' },
    { id: 10, name: 'Lettuce', description: 'A leafy green vegetable used in salads.' },
    { id: 11, name: 'Spinach', description: 'A leafy green vegetable rich in iron and vitamins.' },
    { id: 12, name: 'Cabbage', description: 'A leafy vegetable used in cooking and salads.' },
    { id: 13, name: 'Broccoli', description: 'A cruciferous vegetable rich in vitamins and minerals.' },
    { id: 14, name: 'Cauliflower', description: 'A cruciferous vegetable used in cooking and salads.' },
    { id: 15, name: 'Peppers', description: 'A fruit used in cooking and salads, available in various colors and flavors.' },
    { id: 16, name: 'Cucumbers', description: 'A fruit used in salads and pickling.' },
    { id: 17, name: 'Zucchini', description: 'A summer squash used in cooking and baking.' },
    { id: 18, name: 'Eggplants', description: 'A fruit used in cooking and baking, also known as aubergine.' },
    { id: 19, name: 'Pumpkins', description: 'A fruit used in cooking and baking, often associated with Halloween.' },
    { id: 20, name: 'Watermelons', description: 'A large fruit with a sweet, juicy interior and a hard rind.' },
    { id: 21, name: 'Strawberries', description: 'A sweet, red fruit used in desserts and salads.' },
    { id: 22, name: 'Blueberries', description: 'A small, sweet fruit used in desserts and smoothies.' },
    { id: 23, name: 'Raspberries', description: 'A small, tart fruit used in desserts and jams.' },
    { id: 24, name: 'Blackberries', description: 'A small, sweet fruit used in desserts and jams.' },
    { id: 25, name: 'Grapes', description: 'A small, sweet fruit used in wine production and as a snack.' },
    { id: 26, name: 'Apples', description: 'A sweet or tart fruit used in cooking and baking.' },
    { id: 27, name: 'Pears', description: 'A sweet fruit used in cooking and baking.' },
    { id: 28, name: 'Peaches', description: 'A sweet fruit used in cooking and baking.' },
    { id: 29, name: 'Plums', description: 'A sweet or tart fruit used in cooking and baking.' },
    { id: 30, name: 'Cherries', description: 'A sweet or tart fruit used in cooking and baking.' },
    { id: 31, name: 'Pineapples', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 32, name: 'mango', description: 'A tropical fruit with a sweet and juicy flavor.' },
    { id: 33, name: 'Bananas', description: 'A tropical fruit with a sweet and creamy flavor.' },
    { id: 34, name: 'Oranges', description: 'A citrus fruit with a sweet and tangy flavor.' },
    { id: 35, name: 'Lemons', description: 'A citrus fruit with a sour and tangy flavor.' },
    { id: 36, name: 'Limes', description: 'A citrus fruit with a sour and tangy flavor.' },
    { id: 37, name: 'Grapefruits', description: 'A citrus fruit with a sweet and tangy flavor.' },
    { id: 38, name: 'Kiwis', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 39, name: 'Pomegranates', description: 'A fruit with a sweet and tart flavor, known for its seeds.' },
    { id: 40, name: 'Coconuts', description: 'A tropical fruit with a sweet and creamy flavor, used for its water and meat.' },
    { id: 41, name: 'Avocados', description: 'A fruit with a creamy texture and mild flavor, used in salads and spreads.' },
    { id: 42, name: 'Dates', description: 'A sweet fruit used in cooking and baking, often dried.' },
    { id: 43, name: 'Figs', description: 'A sweet fruit used in cooking and baking, often dried.' },
    { id: 44, name: 'Raisins', description: 'Dried grapes used in cooking and baking.' },
    { id: 45, name: 'Prunes', description: 'Dried plums used in cooking and baking.' },
    { id: 46, name: 'Apricots', description: 'A sweet fruit used in cooking and baking, often dried.' },
    { id: 47, name: 'Nectarines', description: 'A sweet fruit used in cooking and baking.' },
    { id: 48, name: 'Cranberries', description: 'A tart fruit used in cooking and baking, often dried.' },
    { id: 49, name: 'Gooseberries', description: 'A tart fruit used in cooking and baking.' },
    { id: 50, name: 'Currants', description: 'A tart fruit used in cooking and baking, often dried.' },
    { id: 51, name: 'Elderberries', description: 'A tart fruit used in cooking and baking, often dried.' },
    { id: 52, name: 'Mulberries', description: 'A sweet fruit used in cooking and baking.' },
    { id: 53, name: 'Boysenberries', description: 'A sweet fruit used in cooking and baking.' },
    { id: 54, name: 'Loganberries', description: 'A sweet fruit used in cooking and baking.' },
    { id: 55, name: 'Tamarinds', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 56, name: 'Passionfruits', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 57, name: 'Guavas', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 58, name: 'Papayas', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 59, name: 'Jackfruits', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 60, name: 'Durian', description: 'A tropical fruit with a strong odor and unique flavor.' },
    { id: 61, name: 'Lychees', description: 'A tropical fruit with a sweet and floral flavor.' },
    { id: 62, name: 'Rambutans', description: 'A tropical fruit with a sweet and juicy flavor.' },
    { id: 63, name: 'Longans', description: 'A tropical fruit with a sweet and juicy flavor.' },
    { id: 64, name: 'Mangosteens', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 65, name: 'Starfruits', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 66, name: 'Persimmons', description: 'A sweet fruit used in cooking and baking.' },
    { id: 67, name: 'Quinces', description: 'A tart fruit used in cooking and baking.' },
    { id: 68, name: 'Medlars', description: 'A tart fruit used in cooking and baking.' },
    { id: 69, name: 'Loquats', description: 'A sweet fruit used in cooking and baking.' },
    { id: 70, name: 'Jujubes', description: 'A sweet fruit used in cooking and baking.' },
    { id: 71, name: 'Soursops', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 72, name: 'Cherimoyas', description: 'A tropical fruit with a sweet and creamy flavor.' },
    { id: 73, name: 'Feijoas', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 74, name: 'Salak', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 75, name: 'Sapodillas', description: 'A tropical fruit with a sweet and creamy flavor.' },
    { id: 76, name: 'Tamarillos', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 77, name: 'Horned Melons', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 78, name: 'Kiwano', description: 'A tropical fruit with a sweet and tangy flavor.' },
    { id: 79, name: 'Pawpaws', description: 'A tropical fruit with a sweet and creamy flavor.' },
    { id: 80, name: 'Camu Camu', description: 'A tropical fruit with a tart and tangy flavor.' },
    { id: 81, name: 'Acerola', description: 'A tropical fruit with a tart and tangy flavor.' },
    { id: 82, name: 'Barbados Cherries', description: 'A tropical fruit with a tart and tangy flavor.' },
    { id: 83, name: 'Black Sapote', description: 'A tropical fruit with a sweet and creamy flavor.' },
    { id: 84, name: 'White Sapote', description: 'A tropical fruit with a sweet and creamy flavor.' },
    { id: 85, name: 'Buddha\'s Hand', description: 'A citrus fruit with a strong aroma and unique shape, used for flavoring and garnishing.' },
    { id: 86, name: 'Finger Limes', description: 'A citrus fruit with a tart and tangy flavor, used for flavoring and garnishing.' },
    { id: 87, name: 'Kaffir Limes', description: 'A citrus fruit with a strong aroma and unique shape, used for flavoring and garnishing.' },
    { id: 88, name: 'Meyer Lemons', description: 'A citrus fruit with a sweet and mild flavor, used for flavoring and garnishing.'},
    { id: 89, name: 'Rangpur Limes', description: 'A citrus fruit with a tart and tangy flavor, used for flavoring and garnishing.'}
  ];

  constructor() {}
  getCrops() {
    return this.corps;
  }

}
